---
- name: "Configure jenkins localhost"
  hosts: localhost
  connection: local
  become: yes
  gather_facts: yes

  vars_files:
    - vars/main.yml

  roles:
    - geerlingguy.firewall
    # - geerlingguy.ntp
    # - geerlingguy.git
    # - geerlingguy.java
    # - geerlingguy.jenkins  
      
  tasks:
    - name: "OS fingerprinting "
      debug:
        msg:
        - " ansible_os_family: {{ hostvars[inventory_hostname].ansible_os_family }} "
        - " ansible_distribution: {{ hostvars[inventory_hostname].ansible_distribution }}"
        - " ansible_distribution_major_version: {{ hostvars[inventory_hostname].ansible_distribution_major_version }}"
        - " ansible_distribution_release: {{ hostvars[inventory_hostname].ansible_distribution_release }}"
        - " ansible_distribution_version: {{ hostvars[inventory_hostname].ansible_distribution_version }}"
        - " hostname is {{ ansible_hostname }}"

      
