name: "ubuntu 22.04 osquery CI workflow"


on:
  push:
    branches: [ main ]
  schedule:
      - cron:  '0 0 1 * *' ##execution of a task in the first minute of the month


jobs:


  ubuntu-2004-job:
    name: "osquery on ubuntu-22.04"
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: hostnamectl status 
    - name: "install osquery"
      run: sudo sh scripts/install_osquery.sh      
    - name: "DFIR osquery list"
      run: sh scripts/dfir_osquery.sh        


