name: "ubuntu OpenSCAP CI workflow"


on:
  push:
    branches: [ test ]

jobs:

  ubuntu-1804-job:
    name: "OpenSCAP on ubuntu-18.04"
    runs-on: ubuntu-18.04
    env:
      distribution: "ubuntu"
      version: "bionic"   
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: hostnamectl status  
    - name: "Run OpenSCAP audit"
      run: |
        sudo apt-get update -yq
        sudo apt-get install libopenscap8 wget  -yq
        # download the necessary OVAL definitions
        if wget --spider https://people.canonical.com/~ubuntu-security/oval/com.ubuntu.${version}.cve.oval.xml 2>/dev/null; then
          echo "OVAL file exists"
        else
          echo "OVAL file does not exist"
        fi        
        wget https://people.canonical.com/~ubuntu-security/oval/com.ubuntu.${version}.cve.oval.xml
        # Run the audit 
        # https://wiki.ubuntu.com/Releases
        oscap oval eval --results /tmp/${version}_oscap_results.xml --report /tmp/${version}_oscap_report.html com.ubuntu.${version}.cve.oval.xml
        sudo cp /tmp/${version}_oscap_report.html /var/www/html/
        # browse http://SERVER_IP/${version}_oscap_report.html
        
  ubuntu-2004-job:
    name: "OpenSCAP on ubuntu-20.04"
    runs-on: ubuntu-20.04
    env:
      distribution: "ubuntu"
      version: "focal"   
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: hostnamectl status  
    - name: "Run OpenSCAP audit"
      run: |
        sudo apt-get update -yq
        sudo apt-get install libopenscap8 wget  -yq
        # download the necessary OVAL definitions
        if wget --spider https://people.canonical.com/~ubuntu-security/oval/com.ubuntu.${version}.cve.oval.xml 2>/dev/null; then
          echo "OVAL file exists"
        else
          echo "OVAL file does not exist"
        fi        
        wget https://people.canonical.com/~ubuntu-security/oval/com.ubuntu.${version}.cve.oval.xml
        # Run the audit 
        # https://wiki.ubuntu.com/Releases
        oscap oval eval --results /tmp/${version}_oscap_results.xml --report /tmp/${version}_oscap_report.html com.ubuntu.${version}.cve.oval.xml
        sudo cp /tmp/${version}_oscap_report.html /var/www/html/
        # browse http://SERVER_IP/${version}_oscap_report.html        
