name: "osquery matrix CI workflow"


on:
  push:
    branches: [ main ]
  schedule:
      - cron:  '0 0 1 * *' ##execution of a task in the first minute of the month


jobs:

  ubuntu-os-matrix:
      name: "ubuntu os matrix"
      strategy:
        matrix:
        # https://github.com/actions/virtual-environments
          os: [ubuntu-latest,ubuntu-22.04,ubuntu-20.04,ubuntu-18.04]
      runs-on: ${{ matrix.os }} 
      steps:
      - uses: actions/checkout@v2
      - name: "os fingerprinting"
        run: hostnamectl status  
      - name: "install osquery"
        run: sudo sh scripts/install_osquery.sh      
      - name: "DFIR osquery list"
        run: sh scripts/dfir_osquery.sh         
       
