name: "ubuntu ansible CI workflow"


on:
  push:
    branches: [ test ]

jobs:

  # ubuntu-1604-job:
  #   name: "osquery on ubuntu-16.04"
  #   runs-on: ubuntu-16.04
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: "os fingerprinting"
  #     run: hostnamectl status  
  #   - name: "install osquery"
  #     run: sudo sh scripts/install_osquery.sh      
  #   - name: "DFIR osquery list"
  #     run: sh scripts/dfir_osquery.sh   

  # ubuntu-1804-job:
  #   name: "osquery onubuntu-18.04"
  #   runs-on: ubuntu-18.04
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: "os fingerprinting"
  #     run: hostnamectl status  
  #   - name: "install osquery"
  #     run: sudo sh scripts/install_osquery.sh      
  #   - name: "DFIR osquery list"
  #     run: sh scripts/dfir_osquery.sh   

  # ubuntu-2004-job:
  #   name: "osquery on ubuntu-20.04"
  #   runs-on: ubuntu-20.04
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: "os fingerprinting"
  #     run: hostnamectl status 
  #   - name: "install osquery"
  #     run: sudo sh scripts/install_osquery.sh      
  #   - name: "DFIR osquery list"
  #     run: sh scripts/dfir_osquery.sh        

  ubuntu-latest-job:
    name: "ansible on ubuntu-latest"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: hostnamectl status 
    - name: "check on ansible version"
      run: ansible --version

  ubuntu-latest-python-virtualenv-job:
    name: "python-virtualenv ansible on ubuntu-latest"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: hostnamectl status 
    - name: "check on ansible version"
      run: |
        apt list --installed | grep ansible
        # apt-cache search ansible #search repositories for available packages
        # aptitude versions ansible #search repositories for available packages
        # sudo apt-get install -y python-virtualenv
        # python -m virtualenv ansible  # Create a virtualenv if one does not already exist
        # source ansible/bin/activate   # Activate the virtual environment
        # python -m pip install ansible
        # ansible --version

