name: "ubuntu bash packages CI workflow"


on:
  push:
    branches: [ test ]

jobs:

  # ubuntu-1604-job:
  #   name: "osquery on ubuntu-16.04"
  #   runs-on: ubuntu-16.04
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: "os fingerprinting"
  #     run: hostnamectl status  
  #   - name: "install osquery"
  #     run: sudo sh scripts/install_osquery.sh      
  #   - name: "DFIR osquery list"
  #     run: sh scripts/dfir_osquery.sh   

  # ubuntu-1804-job:
  #   name: "osquery onubuntu-18.04"
  #   runs-on: ubuntu-18.04
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: "os fingerprinting"
  #     run: hostnamectl status  
  #   - name: "install osquery"
  #     run: sudo sh scripts/install_osquery.sh      
  #   - name: "DFIR osquery list"
  #     run: sh scripts/dfir_osquery.sh   

  # ubuntu-2004-job:
  #   name: "osquery on ubuntu-20.04"
  #   runs-on: ubuntu-20.04
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: "os fingerprinting"
  #     run: hostnamectl status 
  #   - name: "install osquery"
  #     run: sudo sh scripts/install_osquery.sh      
  #   - name: "DFIR osquery list"
  #     run: sh scripts/dfir_osquery.sh        

  ubuntu-latest-radamsa-job:
    name: "radamsa on ubuntu-latest"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: hostnamectl status    
    - name: "deploy radamsa"
      run: sudo make deploy-radamsa

  ubuntu-latest-kafl-job:
    name: "kafl on ubuntu-latest"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: hostnamectl status    
    - name: "deploy kafl"
      run: sudo make deploy-kafl

  # ubuntu-latest-tshark-job:
  #   name: "tshark on ubuntu-latest"
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: "os fingerprinting"
  #     run: hostnamectl status    
  #   - name: "deploy tshark"
  #     run: make deploy-tshark

  # ubuntu-latest-snmpv3-job:
  #   name: "snmpv3 on ubuntu-latest"
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: "os fingerprinting"
  #     run: hostnamectl status    
  #   - name: "deploy snmp v3"
  #     run: make deploy-snmpv3

  # ubuntu-latest-mrtg-job:
  #   name: "mrtg on ubuntu-latest"
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: "os fingerprinting"
  #     run: hostnamectl status 
  #   - name: "deploy mrtg"
  #     run: make deploy-mrtg       
     

  # ubuntu-latest-nipap-job:
  #   name: "nipap on ubuntu-latest"
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: "os fingerprinting"
  #     run: hostnamectl status       
  #   - name: "deploy nipap"
  #     run: make deploy-nipap      
 
  # ubuntu-latest-ncpa-job:
  #   name: "ncpa on ubuntu-latest"
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: "os fingerprinting"
  #     run: hostnamectl status       
  #   - name: "deploy ncpa"
  #     run: make deploy-ncpa     